### ISSUE TITLE
Start Adding Style

### ISSUE THREAD

**Issue by vtepliuk** [vtepliuk/id.mkdevops.se#1]
#### TODO:

* [x] Review changes in [upstream pull request #10](https://github.com/libris/xl_auth/pull/10)
* [x] Switch local development branch to *feature/issue-9-email-as-username* from upstream repo
* [x] Run through the "verify it works" steps from  [pull request #10](https://github.com/libris/xl_auth/pull/10) and make sure it's possible to register and login
* [x] Checkout a new local *feature/kb-logo* branch from *feature/issue-9-email...*
* [ ] Super-carefully review Fredrik's links from [upstream styling issue](https://github.com/libris/xl_auth/issues/6), both the written guide and the repo codes
* [ ] Commit and push the changes necessary to add the fancy KB logo to login page
* [ ] Tell Mats all about the new insights :1st_place_medal:

**Comment by mblomdahl** [comment]
@vtepliuk Review what this was about, recall the details, then label the issue as "Won't Fix" and close it.

**Comment by vtepliuk** [comment]
> @vtepliuk Review what this was about, recall the details, then label the issue as "Won't Fix" and close it.

OK
